In [10]:
import numpy as np

In [11]:
a = np.array([[1,2,3],
                [4,5,6]])

In [12]:
a.sum(axis=1) #Column

array([ 6, 15])

In [13]:
a.sum(axis=0) # Rows

array([5, 7, 9])

In [14]:
b = np.array([[7,8,9],
              [2,8,0]])

In [19]:
np.dot( a, b.transpose())

array([[ 50,  18],
       [122,  48]])

In [20]:
len(dir(np))

597

In [18]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [21]:
a = np.array([[11,2,3],
              [4,15,6]])

In [23]:
np.sort(a, axis=0)

array([[ 4,  2,  3],
       [11, 15,  6]])

In [24]:
%%time
np.sort(a, axis=0, kind='mergesort')

CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 10.1 ms


array([[ 4,  2,  3],
       [11, 15,  6]])

In [25]:
%%time
np.sort(a, axis=0, kind ='quicksort')

CPU times: user 321 µs, sys: 949 µs, total: 1.27 ms
Wall time: 5.43 ms


array([[ 4,  2,  3],
       [11, 15,  6]])