In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.arange(1,10)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=9
c=90
arr=np.arange(0,11)

In [ ]:
arr
print(arr)
arr
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr[6]

6

In [ ]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(arr[:8])
arr[5:]

[0 1 2 3 4 5 6 7]


array([5, 6, 7, 8, 9])

In [ ]:
slice_off_arr = arr[3:8]
slice_off_arr

array([3, 4, 5, 6, 7])

In [ ]:
#arr[:]=400
arr[0:7]=100

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:5]=100

In [ ]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
arr[arr>9]

array([], dtype=int64)

In [ ]:
a=arr.copy()
z=a

In [ ]:
arr_copy=arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:8]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100,   8,   9])

In [ ]:
arr[arr>50]

array([100, 100, 100, 100, 100])

In [ ]:
#d dimensional array


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[2:, 1:]


array([[8, 9]])

In [ ]:
arr_2d[ 1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr_2d[:2,:1]

array([[1],
       [4]])

In [ ]:
arr_2d=np.arange(30).reshape(10,3) # 3 is row and 10 is column.
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr_2d[0:,4:6]

array([], shape=(10, 0), dtype=int64)

In [ ]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d[6:29]

array([], shape=(0, 10), dtype=int64)

In [ ]:
arr_2d[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
print(arr)
arr-100

[  0   1   2 100 100 100 100 100   8   9]


array([-100,  -99,  -98,    0,    0,    0,    0,    0,  -92,  -91])

In [ ]:
arr/arr

<ipython-input-46-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9,  10])

In [ ]:
arr1=10
arr2=20
arr3=arr1+arr
arr3

array([ 10,  11,  12, 110, 110, 110, 110, 110,  18,  19])

In [ ]:
arr**2

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,    64,
          81,   100])

In [ ]:
np.sqrt(arr) # Square root.

array([10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        ,  2.82842712,  3.        ,
        3.16227766])

In [ ]:
np.exp(arr) #explonential

array([2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

100

In [ ]:
np.min(arr)

8

In [ ]:
np.log(arr)

array([4.60517019, 4.60517019, 4.60517019, 4.60517019, 4.60517019,
       4.60517019, 4.60517019, 4.60517019, 2.07944154, 2.19722458,
       2.30258509])